#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QPushButton *btnBook;
    QPushButton *btnCancel;
    QPushButton *btnReset;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *lblA1;
    QLabel *lblA2;
    QLabel *lblA3;
    QLabel *lblA5;
    QLabel *lblA6;
    QLabel *lblA4;
    QLabel *lblA8;
    QLabel *lblA9;
    QLabel *lblA7;
    QLabel *lblA12;
    QLabel *lblA11;
    QLabel *lblA10;
    QLabel *lblB2;
    QLabel *lblB6;
    QLabel *lblB11;
    QLabel *lblB3;
    QLabel *lblB7;
    QLabel *lblB1;
    QLabel *lblB9;
    QLabel *lblB12;
    QLabel *lblB4;
    QLabel *lblB10;
    QLabel *lblB5;
    QLabel *lblB8;
    QLabel *lblC4;
    QLabel *lblC8;
    QLabel *lblC13;
    QLabel *lblC5;
    QLabel *lblC9;
    QLabel *lblC3;
    QLabel *lblC11;
    QLabel *lblC14;
    QLabel *lblC6;
    QLabel *lblC12;
    QLabel *lblC7;
    QLabel *lblC10;
    QLabel *lblD4;
    QLabel *lblD8;
    QLabel *lblD13;
    QLabel *lblD5;
    QLabel *lblD9;
    QLabel *lblD3;
    QLabel *lblD11;
    QLabel *lblD14;
    QLabel *lblD6;
    QLabel *lblD12;
    QLabel *lblD7;
    QLabel *lblD10;
    QLabel *lblE4;
    QLabel *lblE8;
    QLabel *lblE13;
    QLabel *lblE5;
    QLabel *lblE9;
    QLabel *lblE3;
    QLabel *lblE11;
    QLabel *lblE14;
    QLabel *lblE6;
    QLabel *lblE12;
    QLabel *lblE7;
    QLabel *lblE10;
    QLabel *lblC2;
    QLabel *lblC1;
    QLabel *lblD1;
    QLabel *lblD2;
    QLabel *lblE1;
    QLabel *lblE2;
    QLabel *lblInfoImage;
    QLabel *label_4;
    QFrame *line;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName("MainWindow");
        MainWindow->resize(760, 477);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName("centralWidget");
        btnBook = new QPushButton(centralWidget);
        btnBook->setObjectName("btnBook");
        btnBook->setGeometry(QRect(520, 10, 71, 51));
        btnCancel = new QPushButton(centralWidget);
        btnCancel->setObjectName("btnCancel");
        btnCancel->setGeometry(QRect(600, 10, 71, 51));
        btnReset = new QPushButton(centralWidget);
        btnReset->setObjectName("btnReset");
        btnReset->setGeometry(QRect(680, 10, 71, 51));
        label = new QLabel(centralWidget);
        label->setObjectName("label");
        label->setGeometry(QRect(720, 70, 31, 16));
        QFont font;
        font.setPointSize(10);
        label->setFont(font);
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(10, 70, 31, 16));
        label_2->setFont(font);
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(80, 10, 411, 51));
        label_3->setFrameShape(QFrame::Box);
        label_3->setFrameShadow(QFrame::Raised);
        label_3->setAlignment(Qt::AlignJustify|Qt::AlignVCenter);
        lblA1 = new QLabel(centralWidget);
        lblA1->setObjectName("lblA1");
        lblA1->setGeometry(QRect(610, 140, 35, 35));
        lblA1->setFrameShape(QFrame::Box);
        lblA1->setAlignment(Qt::AlignCenter);
        lblA2 = new QLabel(centralWidget);
        lblA2->setObjectName("lblA2");
        lblA2->setGeometry(QRect(560, 140, 35, 35));
        lblA2->setFrameShape(QFrame::Box);
        lblA2->setAlignment(Qt::AlignCenter);
        lblA3 = new QLabel(centralWidget);
        lblA3->setObjectName("lblA3");
        lblA3->setGeometry(QRect(510, 140, 35, 35));
        lblA3->setFrameShape(QFrame::Box);
        lblA3->setAlignment(Qt::AlignCenter);
        lblA5 = new QLabel(centralWidget);
        lblA5->setObjectName("lblA5");
        lblA5->setGeometry(QRect(410, 140, 35, 35));
        lblA5->setFrameShape(QFrame::Box);
        lblA5->setAlignment(Qt::AlignCenter);
        lblA6 = new QLabel(centralWidget);
        lblA6->setObjectName("lblA6");
        lblA6->setGeometry(QRect(360, 140, 35, 35));
        lblA6->setFrameShape(QFrame::Box);
        lblA6->setAlignment(Qt::AlignCenter);
        lblA4 = new QLabel(centralWidget);
        lblA4->setObjectName("lblA4");
        lblA4->setGeometry(QRect(460, 140, 35, 35));
        lblA4->setFrameShape(QFrame::Box);
        lblA4->setAlignment(Qt::AlignCenter);
        lblA8 = new QLabel(centralWidget);
        lblA8->setObjectName("lblA8");
        lblA8->setGeometry(QRect(260, 140, 35, 35));
        lblA8->setFrameShape(QFrame::Box);
        lblA8->setAlignment(Qt::AlignCenter);
        lblA9 = new QLabel(centralWidget);
        lblA9->setObjectName("lblA9");
        lblA9->setGeometry(QRect(210, 140, 35, 35));
        lblA9->setFrameShape(QFrame::Box);
        lblA9->setAlignment(Qt::AlignCenter);
        lblA7 = new QLabel(centralWidget);
        lblA7->setObjectName("lblA7");
        lblA7->setGeometry(QRect(310, 140, 35, 35));
        lblA7->setFrameShape(QFrame::Box);
        lblA7->setAlignment(Qt::AlignCenter);
        lblA12 = new QLabel(centralWidget);
        lblA12->setObjectName("lblA12");
        lblA12->setGeometry(QRect(10, 140, 35, 35));
        lblA12->setFrameShape(QFrame::Box);
        lblA12->setAlignment(Qt::AlignCenter);
        lblA11 = new QLabel(centralWidget);
        lblA11->setObjectName("lblA11");
        lblA11->setGeometry(QRect(60, 140, 35, 35));
        lblA11->setFrameShape(QFrame::Box);
        lblA11->setAlignment(Qt::AlignCenter);
        lblA10 = new QLabel(centralWidget);
        lblA10->setObjectName("lblA10");
        lblA10->setGeometry(QRect(160, 140, 35, 35));
        lblA10->setFrameShape(QFrame::Box);
        lblA10->setAlignment(Qt::AlignCenter);
        lblB2 = new QLabel(centralWidget);
        lblB2->setObjectName("lblB2");
        lblB2->setGeometry(QRect(560, 200, 35, 35));
        lblB2->setFrameShape(QFrame::Box);
        lblB2->setAlignment(Qt::AlignCenter);
        lblB6 = new QLabel(centralWidget);
        lblB6->setObjectName("lblB6");
        lblB6->setGeometry(QRect(360, 200, 35, 35));
        lblB6->setFrameShape(QFrame::Box);
        lblB6->setAlignment(Qt::AlignCenter);
        lblB11 = new QLabel(centralWidget);
        lblB11->setObjectName("lblB11");
        lblB11->setGeometry(QRect(60, 200, 35, 35));
        lblB11->setFrameShape(QFrame::Box);
        lblB11->setAlignment(Qt::AlignCenter);
        lblB3 = new QLabel(centralWidget);
        lblB3->setObjectName("lblB3");
        lblB3->setGeometry(QRect(510, 200, 35, 35));
        lblB3->setFrameShape(QFrame::Box);
        lblB3->setAlignment(Qt::AlignCenter);
        lblB7 = new QLabel(centralWidget);
        lblB7->setObjectName("lblB7");
        lblB7->setGeometry(QRect(310, 200, 35, 35));
        lblB7->setFrameShape(QFrame::Box);
        lblB7->setAlignment(Qt::AlignCenter);
        lblB1 = new QLabel(centralWidget);
        lblB1->setObjectName("lblB1");
        lblB1->setGeometry(QRect(610, 200, 35, 35));
        lblB1->setFrameShape(QFrame::Box);
        lblB1->setAlignment(Qt::AlignCenter);
        lblB9 = new QLabel(centralWidget);
        lblB9->setObjectName("lblB9");
        lblB9->setGeometry(QRect(210, 200, 35, 35));
        lblB9->setFrameShape(QFrame::Box);
        lblB9->setAlignment(Qt::AlignCenter);
        lblB12 = new QLabel(centralWidget);
        lblB12->setObjectName("lblB12");
        lblB12->setGeometry(QRect(10, 200, 35, 35));
        lblB12->setFrameShape(QFrame::Box);
        lblB12->setAlignment(Qt::AlignCenter);
        lblB4 = new QLabel(centralWidget);
        lblB4->setObjectName("lblB4");
        lblB4->setGeometry(QRect(460, 200, 35, 35));
        lblB4->setFrameShape(QFrame::Box);
        lblB4->setAlignment(Qt::AlignCenter);
        lblB10 = new QLabel(centralWidget);
        lblB10->setObjectName("lblB10");
        lblB10->setGeometry(QRect(160, 200, 35, 35));
        lblB10->setFrameShape(QFrame::Box);
        lblB10->setAlignment(Qt::AlignCenter);
        lblB5 = new QLabel(centralWidget);
        lblB5->setObjectName("lblB5");
        lblB5->setGeometry(QRect(410, 200, 35, 35));
        lblB5->setFrameShape(QFrame::Box);
        lblB5->setAlignment(Qt::AlignCenter);
        lblB8 = new QLabel(centralWidget);
        lblB8->setObjectName("lblB8");
        lblB8->setGeometry(QRect(260, 200, 35, 35));
        lblB8->setFrameShape(QFrame::Box);
        lblB8->setAlignment(Qt::AlignCenter);
        lblC4 = new QLabel(centralWidget);
        lblC4->setObjectName("lblC4");
        lblC4->setGeometry(QRect(560, 260, 35, 35));
        lblC4->setFrameShape(QFrame::Box);
        lblC4->setAlignment(Qt::AlignCenter);
        lblC8 = new QLabel(centralWidget);
        lblC8->setObjectName("lblC8");
        lblC8->setGeometry(QRect(360, 260, 35, 35));
        lblC8->setFrameShape(QFrame::Box);
        lblC8->setAlignment(Qt::AlignCenter);
        lblC13 = new QLabel(centralWidget);
        lblC13->setObjectName("lblC13");
        lblC13->setGeometry(QRect(60, 260, 35, 35));
        lblC13->setFrameShape(QFrame::Box);
        lblC13->setAlignment(Qt::AlignCenter);
        lblC5 = new QLabel(centralWidget);
        lblC5->setObjectName("lblC5");
        lblC5->setGeometry(QRect(510, 260, 35, 35));
        lblC5->setFrameShape(QFrame::Box);
        lblC5->setAlignment(Qt::AlignCenter);
        lblC9 = new QLabel(centralWidget);
        lblC9->setObjectName("lblC9");
        lblC9->setGeometry(QRect(310, 260, 35, 35));
        lblC9->setFrameShape(QFrame::Box);
        lblC9->setAlignment(Qt::AlignCenter);
        lblC3 = new QLabel(centralWidget);
        lblC3->setObjectName("lblC3");
        lblC3->setGeometry(QRect(610, 260, 35, 35));
        lblC3->setFrameShape(QFrame::Box);
        lblC3->setAlignment(Qt::AlignCenter);
        lblC11 = new QLabel(centralWidget);
        lblC11->setObjectName("lblC11");
        lblC11->setGeometry(QRect(210, 260, 35, 35));
        lblC11->setFrameShape(QFrame::Box);
        lblC11->setAlignment(Qt::AlignCenter);
        lblC14 = new QLabel(centralWidget);
        lblC14->setObjectName("lblC14");
        lblC14->setGeometry(QRect(10, 260, 35, 35));
        lblC14->setFrameShape(QFrame::Box);
        lblC14->setAlignment(Qt::AlignCenter);
        lblC6 = new QLabel(centralWidget);
        lblC6->setObjectName("lblC6");
        lblC6->setGeometry(QRect(460, 260, 35, 35));
        lblC6->setFrameShape(QFrame::Box);
        lblC6->setAlignment(Qt::AlignCenter);
        lblC12 = new QLabel(centralWidget);
        lblC12->setObjectName("lblC12");
        lblC12->setGeometry(QRect(160, 260, 35, 35));
        lblC12->setFrameShape(QFrame::Box);
        lblC12->setAlignment(Qt::AlignCenter);
        lblC7 = new QLabel(centralWidget);
        lblC7->setObjectName("lblC7");
        lblC7->setGeometry(QRect(410, 260, 35, 35));
        lblC7->setFrameShape(QFrame::Box);
        lblC7->setAlignment(Qt::AlignCenter);
        lblC10 = new QLabel(centralWidget);
        lblC10->setObjectName("lblC10");
        lblC10->setGeometry(QRect(260, 260, 35, 35));
        lblC10->setFrameShape(QFrame::Box);
        lblC10->setAlignment(Qt::AlignCenter);
        lblD4 = new QLabel(centralWidget);
        lblD4->setObjectName("lblD4");
        lblD4->setGeometry(QRect(560, 320, 35, 35));
        lblD4->setFrameShape(QFrame::Box);
        lblD4->setAlignment(Qt::AlignCenter);
        lblD8 = new QLabel(centralWidget);
        lblD8->setObjectName("lblD8");
        lblD8->setGeometry(QRect(360, 320, 35, 35));
        lblD8->setFrameShape(QFrame::Box);
        lblD8->setAlignment(Qt::AlignCenter);
        lblD13 = new QLabel(centralWidget);
        lblD13->setObjectName("lblD13");
        lblD13->setGeometry(QRect(60, 320, 35, 35));
        lblD13->setFrameShape(QFrame::Box);
        lblD13->setAlignment(Qt::AlignCenter);
        lblD5 = new QLabel(centralWidget);
        lblD5->setObjectName("lblD5");
        lblD5->setGeometry(QRect(510, 320, 35, 35));
        lblD5->setFrameShape(QFrame::Box);
        lblD5->setAlignment(Qt::AlignCenter);
        lblD9 = new QLabel(centralWidget);
        lblD9->setObjectName("lblD9");
        lblD9->setGeometry(QRect(310, 320, 35, 35));
        lblD9->setFrameShape(QFrame::Box);
        lblD9->setAlignment(Qt::AlignCenter);
        lblD3 = new QLabel(centralWidget);
        lblD3->setObjectName("lblD3");
        lblD3->setGeometry(QRect(610, 320, 35, 35));
        lblD3->setFrameShape(QFrame::Box);
        lblD3->setAlignment(Qt::AlignCenter);
        lblD11 = new QLabel(centralWidget);
        lblD11->setObjectName("lblD11");
        lblD11->setGeometry(QRect(210, 320, 35, 35));
        lblD11->setFrameShape(QFrame::Box);
        lblD11->setAlignment(Qt::AlignCenter);
        lblD14 = new QLabel(centralWidget);
        lblD14->setObjectName("lblD14");
        lblD14->setGeometry(QRect(10, 320, 35, 35));
        lblD14->setFrameShape(QFrame::Box);
        lblD14->setAlignment(Qt::AlignCenter);
        lblD6 = new QLabel(centralWidget);
        lblD6->setObjectName("lblD6");
        lblD6->setGeometry(QRect(460, 320, 35, 35));
        lblD6->setFrameShape(QFrame::Box);
        lblD6->setAlignment(Qt::AlignCenter);
        lblD12 = new QLabel(centralWidget);
        lblD12->setObjectName("lblD12");
        lblD12->setGeometry(QRect(160, 320, 35, 35));
        lblD12->setFrameShape(QFrame::Box);
        lblD12->setAlignment(Qt::AlignCenter);
        lblD7 = new QLabel(centralWidget);
        lblD7->setObjectName("lblD7");
        lblD7->setGeometry(QRect(410, 320, 35, 35));
        lblD7->setFrameShape(QFrame::Box);
        lblD7->setAlignment(Qt::AlignCenter);
        lblD10 = new QLabel(centralWidget);
        lblD10->setObjectName("lblD10");
        lblD10->setGeometry(QRect(260, 320, 35, 35));
        lblD10->setFrameShape(QFrame::Box);
        lblD10->setAlignment(Qt::AlignCenter);
        lblE4 = new QLabel(centralWidget);
        lblE4->setObjectName("lblE4");
        lblE4->setGeometry(QRect(560, 380, 35, 35));
        lblE4->setFrameShape(QFrame::Box);
        lblE4->setAlignment(Qt::AlignCenter);
        lblE8 = new QLabel(centralWidget);
        lblE8->setObjectName("lblE8");
        lblE8->setGeometry(QRect(360, 380, 35, 35));
        lblE8->setFrameShape(QFrame::Box);
        lblE8->setAlignment(Qt::AlignCenter);
        lblE13 = new QLabel(centralWidget);
        lblE13->setObjectName("lblE13");
        lblE13->setGeometry(QRect(60, 380, 35, 35));
        lblE13->setFrameShape(QFrame::Box);
        lblE13->setAlignment(Qt::AlignCenter);
        lblE5 = new QLabel(centralWidget);
        lblE5->setObjectName("lblE5");
        lblE5->setGeometry(QRect(510, 380, 35, 35));
        lblE5->setFrameShape(QFrame::Box);
        lblE5->setAlignment(Qt::AlignCenter);
        lblE9 = new QLabel(centralWidget);
        lblE9->setObjectName("lblE9");
        lblE9->setGeometry(QRect(310, 380, 35, 35));
        lblE9->setFrameShape(QFrame::Box);
        lblE9->setAlignment(Qt::AlignCenter);
        lblE3 = new QLabel(centralWidget);
        lblE3->setObjectName("lblE3");
        lblE3->setGeometry(QRect(610, 380, 35, 35));
        lblE3->setFrameShape(QFrame::Box);
        lblE3->setAlignment(Qt::AlignCenter);
        lblE11 = new QLabel(centralWidget);
        lblE11->setObjectName("lblE11");
        lblE11->setGeometry(QRect(210, 380, 35, 35));
        lblE11->setFrameShape(QFrame::Box);
        lblE11->setAlignment(Qt::AlignCenter);
        lblE14 = new QLabel(centralWidget);
        lblE14->setObjectName("lblE14");
        lblE14->setGeometry(QRect(10, 380, 35, 35));
        lblE14->setFrameShape(QFrame::Box);
        lblE14->setAlignment(Qt::AlignCenter);
        lblE6 = new QLabel(centralWidget);
        lblE6->setObjectName("lblE6");
        lblE6->setGeometry(QRect(460, 380, 35, 35));
        lblE6->setFrameShape(QFrame::Box);
        lblE6->setAlignment(Qt::AlignCenter);
        lblE12 = new QLabel(centralWidget);
        lblE12->setObjectName("lblE12");
        lblE12->setGeometry(QRect(160, 380, 35, 35));
        lblE12->setFrameShape(QFrame::Box);
        lblE12->setAlignment(Qt::AlignCenter);
        lblE7 = new QLabel(centralWidget);
        lblE7->setObjectName("lblE7");
        lblE7->setGeometry(QRect(410, 380, 35, 35));
        lblE7->setFrameShape(QFrame::Box);
        lblE7->setAlignment(Qt::AlignCenter);
        lblE10 = new QLabel(centralWidget);
        lblE10->setObjectName("lblE10");
        lblE10->setGeometry(QRect(260, 380, 35, 35));
        lblE10->setFrameShape(QFrame::Box);
        lblE10->setAlignment(Qt::AlignCenter);
        lblC2 = new QLabel(centralWidget);
        lblC2->setObjectName("lblC2");
        lblC2->setGeometry(QRect(660, 260, 35, 35));
        lblC2->setFrameShape(QFrame::Box);
        lblC2->setAlignment(Qt::AlignCenter);
        lblC1 = new QLabel(centralWidget);
        lblC1->setObjectName("lblC1");
        lblC1->setGeometry(QRect(710, 260, 35, 35));
        lblC1->setFrameShape(QFrame::Box);
        lblC1->setAlignment(Qt::AlignCenter);
        lblD1 = new QLabel(centralWidget);
        lblD1->setObjectName("lblD1");
        lblD1->setGeometry(QRect(710, 320, 35, 35));
        lblD1->setFrameShape(QFrame::Box);
        lblD1->setAlignment(Qt::AlignCenter);
        lblD2 = new QLabel(centralWidget);
        lblD2->setObjectName("lblD2");
        lblD2->setGeometry(QRect(660, 320, 35, 35));
        lblD2->setFrameShape(QFrame::Box);
        lblD2->setAlignment(Qt::AlignCenter);
        lblE1 = new QLabel(centralWidget);
        lblE1->setObjectName("lblE1");
        lblE1->setGeometry(QRect(710, 380, 35, 35));
        lblE1->setFrameShape(QFrame::Box);
        lblE1->setAlignment(Qt::AlignCenter);
        lblE2 = new QLabel(centralWidget);
        lblE2->setObjectName("lblE2");
        lblE2->setGeometry(QRect(660, 380, 35, 35));
        lblE2->setFrameShape(QFrame::Box);
        lblE2->setAlignment(Qt::AlignCenter);
        lblInfoImage = new QLabel(centralWidget);
        lblInfoImage->setObjectName("lblInfoImage");
        lblInfoImage->setGeometry(QRect(330, 423, 101, 41));
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(600, 450, 141, 20));
        QFont font1;
        font1.setPointSize(9);
        label_4->setFont(font1);
        line = new QFrame(centralWidget);
        line->setObjectName("line");
        line->setGeometry(QRect(600, 460, 140, 16));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        MainWindow->setCentralWidget(centralWidget);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "Movie Ticket Booking 1.0", nullptr));
        btnBook->setText(QCoreApplication::translate("MainWindow", "Reserver", nullptr));
        btnCancel->setText(QCoreApplication::translate("MainWindow", "Annuler", nullptr));
        btnReset->setText(QCoreApplication::translate("MainWindow", "Fin Film", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "EXIT", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "EXIT", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "                                                             Ecran", nullptr));
        lblA1->setText(QCoreApplication::translate("MainWindow", "A-1", nullptr));
        lblA2->setText(QCoreApplication::translate("MainWindow", "A-2", nullptr));
        lblA3->setText(QCoreApplication::translate("MainWindow", "A-3", nullptr));
        lblA5->setText(QCoreApplication::translate("MainWindow", "A-5", nullptr));
        lblA6->setText(QCoreApplication::translate("MainWindow", "A-6", nullptr));
        lblA4->setText(QCoreApplication::translate("MainWindow", "A-4", nullptr));
        lblA8->setText(QCoreApplication::translate("MainWindow", "A-8", nullptr));
        lblA9->setText(QCoreApplication::translate("MainWindow", "A-9", nullptr));
        lblA7->setText(QCoreApplication::translate("MainWindow", "A-7", nullptr));
        lblA12->setText(QCoreApplication::translate("MainWindow", "A-12", nullptr));
        lblA11->setText(QCoreApplication::translate("MainWindow", "A-11", nullptr));
        lblA10->setText(QCoreApplication::translate("MainWindow", "A-10", nullptr));
        lblB2->setText(QCoreApplication::translate("MainWindow", "B-2", nullptr));
        lblB6->setText(QCoreApplication::translate("MainWindow", "B-6", nullptr));
        lblB11->setText(QCoreApplication::translate("MainWindow", "B-11", nullptr));
        lblB3->setText(QCoreApplication::translate("MainWindow", "B-3", nullptr));
        lblB7->setText(QCoreApplication::translate("MainWindow", "B-7", nullptr));
        lblB1->setText(QCoreApplication::translate("MainWindow", "B-1", nullptr));
        lblB9->setText(QCoreApplication::translate("MainWindow", "B-9", nullptr));
        lblB12->setText(QCoreApplication::translate("MainWindow", "B-12", nullptr));
        lblB4->setText(QCoreApplication::translate("MainWindow", "B-4", nullptr));
        lblB10->setText(QCoreApplication::translate("MainWindow", "B-10", nullptr));
        lblB5->setText(QCoreApplication::translate("MainWindow", "B-5", nullptr));
        lblB8->setText(QCoreApplication::translate("MainWindow", "B-8", nullptr));
        lblC4->setText(QCoreApplication::translate("MainWindow", "C-4", nullptr));
        lblC8->setText(QCoreApplication::translate("MainWindow", "C-8", nullptr));
        lblC13->setText(QCoreApplication::translate("MainWindow", "C-13", nullptr));
        lblC5->setText(QCoreApplication::translate("MainWindow", "C-5", nullptr));
        lblC9->setText(QCoreApplication::translate("MainWindow", "C-9", nullptr));
        lblC3->setText(QCoreApplication::translate("MainWindow", "C-3", nullptr));
        lblC11->setText(QCoreApplication::translate("MainWindow", "C-11", nullptr));
        lblC14->setText(QCoreApplication::translate("MainWindow", "C-14", nullptr));
        lblC6->setText(QCoreApplication::translate("MainWindow", "C-6", nullptr));
        lblC12->setText(QCoreApplication::translate("MainWindow", "C-12", nullptr));
        lblC7->setText(QCoreApplication::translate("MainWindow", "C-7", nullptr));
        lblC10->setText(QCoreApplication::translate("MainWindow", "C-10", nullptr));
        lblD4->setText(QCoreApplication::translate("MainWindow", "D-4", nullptr));
        lblD8->setText(QCoreApplication::translate("MainWindow", "D-8", nullptr));
        lblD13->setText(QCoreApplication::translate("MainWindow", "D-13", nullptr));
        lblD5->setText(QCoreApplication::translate("MainWindow", "D-5", nullptr));
        lblD9->setText(QCoreApplication::translate("MainWindow", "D-9", nullptr));
        lblD3->setText(QCoreApplication::translate("MainWindow", "D-3", nullptr));
        lblD11->setText(QCoreApplication::translate("MainWindow", "D-11", nullptr));
        lblD14->setText(QCoreApplication::translate("MainWindow", "D-14", nullptr));
        lblD6->setText(QCoreApplication::translate("MainWindow", "D-6", nullptr));
        lblD12->setText(QCoreApplication::translate("MainWindow", "D-12", nullptr));
        lblD7->setText(QCoreApplication::translate("MainWindow", "D-7", nullptr));
        lblD10->setText(QCoreApplication::translate("MainWindow", "D-10", nullptr));
        lblE4->setText(QCoreApplication::translate("MainWindow", "E-4", nullptr));
        lblE8->setText(QCoreApplication::translate("MainWindow", "E-8", nullptr));
        lblE13->setText(QCoreApplication::translate("MainWindow", "E-13", nullptr));
        lblE5->setText(QCoreApplication::translate("MainWindow", "E-5", nullptr));
        lblE9->setText(QCoreApplication::translate("MainWindow", "E-9", nullptr));
        lblE3->setText(QCoreApplication::translate("MainWindow", "E-3", nullptr));
        lblE11->setText(QCoreApplication::translate("MainWindow", "E-11", nullptr));
        lblE14->setText(QCoreApplication::translate("MainWindow", "E-14", nullptr));
        lblE6->setText(QCoreApplication::translate("MainWindow", "E-6", nullptr));
        lblE12->setText(QCoreApplication::translate("MainWindow", "E-12", nullptr));
        lblE7->setText(QCoreApplication::translate("MainWindow", "E-7", nullptr));
        lblE10->setText(QCoreApplication::translate("MainWindow", "E-10", nullptr));
        lblC2->setText(QCoreApplication::translate("MainWindow", "C-2", nullptr));
        lblC1->setText(QCoreApplication::translate("MainWindow", "C-1", nullptr));
        lblD1->setText(QCoreApplication::translate("MainWindow", "D-1", nullptr));
        lblD2->setText(QCoreApplication::translate("MainWindow", "D-2", nullptr));
        lblE1->setText(QCoreApplication::translate("MainWindow", "E-1", nullptr));
        lblE2->setText(QCoreApplication::translate("MainWindow", "E-2", nullptr));
        lblInfoImage->setText(QString());
        label_4->setText(QCoreApplication::translate("MainWindow", "Project by Chihab & Idris", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
